# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AT-Field
email: Anarchy0316@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  测试 测试 如果能看到这行那你多半是只单身狗
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://weibo.com" # the base hostname & protocol for your site
twitter_username: Anarchy0316
github_username:  Anarchy0316 

# Build settings
markdown: kramdown
