# Site settings
name: Cosmos
email: anarchy0316@gmail.com
author: Jiacheng Chen
url: http://weibo.com/tourbillonc/
weibo: http://weibo.com/tourbillonc/
github: https://github.com/anarchy0316/
baseurl: ""
description: 你好，旅行者。
meta_description: meta_description
motto: Every second matters. 
banner: 施工中 
gems: [jekyll-paginate]

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: anarchy0316
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : anarchy0316
    disqus :
        short_name :    

